# Generated by Django 4.0.3 on 2022-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_gender_alter_user_hasbicycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='hasbicycle',
            field=models.BooleanField(default=b'I00\n'),
        ),
    ]
